### ISSUE TITLE
How do I find the correct format for my city?

### ISSUE THREAD

**Issue by brianhanifin** [xfjx/homebridge-wunderground#2]
I live in Santee, California, in the United States.

**Comment by xfjx** [comment]
Hey,

This should be CA/Santee for city.

Please let me know if it works.

**Comment by xfjx** [comment]
Just checked it. CA/Santee will query this in wunderground:

<display_location>
<full>Santee, CA</full>
<city>Santee</city>
<state>CA</state>
<state_name>California</state_name>
<country>US</country>
<country_iso3166>US</country_iso3166>
<zip>92071</zip>
<magic>1</magic>
<wmo>99999</wmo>
<latitude>32.84790802</latitude>
<longitude>-116.98807526</longitude>
<elevation>104.00000000</elevation>
</display_location>

**Comment by brianhanifin** [comment]
Thank you. Where can you query that information? I can't seem to find it on the WUnderground site.

Here is what I have in my accessory config.

```
{
	"accessory": "WUNDERGROUND",
	"name": "Weather Underground",
	"device": "KCASANTE33",
	"key": "[my developer key]",
	"city": "CA/Santee"
}
```

As soon as Apple's iOS 10 Home app tries to query the weather data, homebridge crashes with the following messages.

```
[9/19/2016, 5:56:43 PM] [Weather Underground] Successfully fetched weather data from wunderground.com
/usr/local/lib/node_modules/homebridge-wunderground/index.js:36
    		that.temperature = response['current_observation']['temp_c'];
    		                                                  ^

TypeError: Cannot read property 'temp_c' of undefined
    at null.<anonymous> (/usr/local/lib/node_modules/homebridge-wunderground/index.js:36:57)
    at Request._callback (/usr/local/lib/node_modules/homebridge-wunderground/node_modules/wundergroundnode/lib/wundergroundnode.js:137:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-wunderground/node_modules/wundergroundnode/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-wunderground/node_modules/wundergroundnode/node_modules/request/request.js:1048:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wunderground/node_modules/wundergroundnode/node_modules/request/request.js:969:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Is this error occurring because my locale uses Fahrenheit instead of Celsius?

**Comment by xfjx** [comment]
You can use this URL to fetch the information with your browser:

http://api.wunderground.com/api/*your_key_here*/conditions/lang:DL/q/CA/Santee.xml

There is always an temp_c and temp_f. Maybe your key is not correct?

**Comment by evitiello** [comment]
Based on the wunderground API docs (https://www.wunderground.com/weather/api/d/docs?d=data/index) it looks like you can use a bunch of different formats:

The location for which you want weather information. Examples:
CA/San_Francisco	US state/city
60290	US zipcode
Australia/Sydney	country/city
37.8,-122.4	latitude,longitude
KJFK	airport code
pws:KCASANFR70	PWS id
autoip	AutoIP address location
autoip.json?geo_ip=38.102.136.138
