### ISSUE TITLE
Still getting crashes

### ISSUE THREAD

**Issue by blalor** [xfjx/homebridge-wunderground#22]
This is 0.0.7.

stdout:
```
[3/16/2018, 6:30:30 AM] [Weather Underground] WUnderground Polling...
[3/16/2018, 6:30:33 AM] [Weather Underground] Error fetching weather data from wunderground.com! Check your connection or configuration.
```

stderr:
```
/Users/blalor/devel/homebridge/node_modules/homebridge-wunderground/index.js:88
                } else if (response['response']['error'] && response['response']['error']['type'] && response['response']['error']['description']) {
                                               ^

TypeError: Cannot read property 'error' of undefined
    at Wunderground.<anonymous> (/Users/blalor/devel/homebridge/node_modules/homebridge-wunderground/index.js:88:48)
    at Request._callback (/Users/blalor/devel/homebridge/node_modules/wundergroundnode/lib/wundergroundnode.js:148:22)
    at Request.self.callback (/Users/blalor/devel/homebridge/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/Users/blalor/devel/homebridge/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/Users/blalor/devel/homebridge/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
```

**Comment by jmissig** [comment]
I've seen this one a few times as well. Should make sure `response['response']` exists before trying to get `['error']` from it.

**Comment by xfjx** [comment]
I submitted another version to npm. I hope this is now fixed.
